# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helix.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'helix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhelix.proto\x12\x08helix.v1\"d\n\x0cQueryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\x12\'\n\x08req_type\x18\x04 \x01(\x0e\x32\x15.helix.v1.RequestType\"P\n\rQueryResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t\"7\n\x0c\x42\x61tchRequest\x12\'\n\x07queries\x18\x01 \x03(\x0b\x32\x16.helix.v1.QueryRequest\"9\n\rBatchResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.helix.v1.QueryResponse*!\n\x0bRequestType\x12\t\n\x05QUERY\x10\x00\x12\x07\n\x03MCP\x10\x01\x32\xc1\x01\n\x07HelixDB\x12\x38\n\x05Query\x12\x16.helix.v1.QueryRequest\x1a\x17.helix.v1.QueryResponse\x12\x38\n\x05\x42\x61tch\x12\x16.helix.v1.BatchRequest\x1a\x17.helix.v1.BatchResponse\x12\x42\n\x0bStreamQuery\x12\x16.helix.v1.QueryRequest\x1a\x17.helix.v1.QueryResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTTYPE']._serialized_start=325
  _globals['_REQUESTTYPE']._serialized_end=358
  _globals['_QUERYREQUEST']._serialized_start=25
  _globals['_QUERYREQUEST']._serialized_end=125
  _globals['_QUERYRESPONSE']._serialized_start=127
  _globals['_QUERYRESPONSE']._serialized_end=207
  _globals['_BATCHREQUEST']._serialized_start=209
  _globals['_BATCHREQUEST']._serialized_end=264
  _globals['_BATCHRESPONSE']._serialized_start=266
  _globals['_BATCHRESPONSE']._serialized_end=323
  _globals['_HELIXDB']._serialized_start=361
  _globals['_HELIXDB']._serialized_end=554
# @@protoc_insertion_point(module_scope)
