# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from engram.storage.helix.proto import helix_pb2 as helix__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in helix_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HelixDBStub(object):
    """HelixDB gRPC service — runs alongside the HTTP gateway on port 6970.
    Shares the same WorkerPool for query execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/helix.v1.HelixDB/Query',
                request_serializer=helix__pb2.QueryRequest.SerializeToString,
                response_deserializer=helix__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Batch = channel.unary_unary(
                '/helix.v1.HelixDB/Batch',
                request_serializer=helix__pb2.BatchRequest.SerializeToString,
                response_deserializer=helix__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.StreamQuery = channel.stream_stream(
                '/helix.v1.HelixDB/StreamQuery',
                request_serializer=helix__pb2.QueryRequest.SerializeToString,
                response_deserializer=helix__pb2.QueryResponse.FromString,
                _registered_method=True)


class HelixDBServicer(object):
    """HelixDB gRPC service — runs alongside the HTTP gateway on port 6970.
    Shares the same WorkerPool for query execution.
    """

    def Query(self, request, context):
        """Single query — equivalent to POST /{endpoint}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Batch(self, request, context):
        """Batch — equivalent to POST /batch, executes queries concurrently
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuery(self, request_iterator, context):
        """Bidirectional stream — for bulk reads (consolidation, corpus loading)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelixDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=helix__pb2.QueryRequest.FromString,
                    response_serializer=helix__pb2.QueryResponse.SerializeToString,
            ),
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=helix__pb2.BatchRequest.FromString,
                    response_serializer=helix__pb2.BatchResponse.SerializeToString,
            ),
            'StreamQuery': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamQuery,
                    request_deserializer=helix__pb2.QueryRequest.FromString,
                    response_serializer=helix__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helix.v1.HelixDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helix.v1.HelixDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelixDB(object):
    """HelixDB gRPC service — runs alongside the HTTP gateway on port 6970.
    Shares the same WorkerPool for query execution.
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helix.v1.HelixDB/Query',
            helix__pb2.QueryRequest.SerializeToString,
            helix__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helix.v1.HelixDB/Batch',
            helix__pb2.BatchRequest.SerializeToString,
            helix__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuery(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/helix.v1.HelixDB/StreamQuery',
            helix__pb2.QueryRequest.SerializeToString,
            helix__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
