use std::io::{BufRead, BufReader};

fn main() {
    // Copy queries.rs from helix-container (generated by helix push)
    let queries_src = std::env::var("HELIX_QUERIES_RS")
        .unwrap_or_else(|_| {
            let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
            let bundled = std::path::Path::new(&manifest_dir).join("src/queries.rs");
            if bundled.exists() {
                bundled.to_string_lossy().to_string()
            } else {
                let path = std::path::Path::new(&manifest_dir)
                    .join("../helix-container/src/queries.rs");
                path.to_string_lossy().to_string()
            }
        });

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = std::path::Path::new(&out_dir).join("queries.rs");

    if std::path::Path::new(&queries_src).exists() {
        std::fs::copy(&queries_src, &dest).expect("Failed to copy queries.rs");
    } else {
        std::fs::write(&dest, r#"
use helix_db::helix_engine::traversal_core::config::Config;
pub fn config() -> Option<Config> { None }
"#).expect("Failed to write default queries.rs");
    }

    // Parse handler names from queries.rs and generate manual route registration.
    // This bypasses inventory::iter which doesn't work reliably in cdylib on macOS.
    let route_map = std::path::Path::new(&out_dir).join("route_map.rs");
    generate_route_map(&dest, &route_map);

    println!("cargo:rerun-if-changed={}", queries_src);
}

fn generate_route_map(queries_path: &std::path::Path, output_path: &std::path::Path) {
    let file = match std::fs::File::open(queries_path) {
        Ok(f) => f,
        Err(_) => {
            std::fs::write(output_path,
                "pub fn register_routes() -> (std::collections::HashMap<String, helix_db::helix_gateway::router::router::HandlerFn>, std::collections::HashSet<String>) { (std::collections::HashMap::new(), std::collections::HashSet::new()) }"
            ).unwrap();
            return;
        }
    };

    let reader = BufReader::new(file);
    let mut handlers: Vec<(String, bool)> = Vec::new(); // (fn_name, is_write)

    for line in reader.lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => continue,
        };
        let trimmed = line.trim();

        if trimmed == "#[handler]" {
            // Next significant line is `pub fn <name>`
            handlers.push((String::new(), false));
        } else if trimmed == "#[handler(is_write)]" {
            handlers.push((String::new(), true));
        } else if trimmed.starts_with("pub fn ") {
            if let Some(entry) = handlers.last_mut() {
                if entry.0.is_empty() {
                    // Extract function name: "pub fn foo_bar (input: ..." -> "foo_bar"
                    let rest = &trimmed[7..]; // skip "pub fn "
                    let name = rest.split(|c: char| !c.is_alphanumeric() && c != '_')
                        .next()
                        .unwrap_or("")
                        .to_string();
                    if !name.is_empty() {
                        entry.0 = name;
                    }
                }
            }
        }
    }

    // Remove entries with empty names (parsing failures)
    handlers.retain(|(name, _)| !name.is_empty());

    let mut code = String::new();
    code.push_str("/// Auto-generated route map - bypasses inventory for cdylib compatibility.\n");
    code.push_str("pub fn register_routes() -> (std::collections::HashMap<String, helix_db::helix_gateway::router::router::HandlerFn>, std::collections::HashSet<String>) {\n");
    code.push_str("    use std::collections::{HashMap, HashSet};\n");
    code.push_str("    use std::sync::Arc;\n");
    code.push_str("    use helix_db::helix_gateway::router::router::HandlerFn;\n");
    code.push_str("    let mut routes: HashMap<String, HandlerFn> = HashMap::new();\n");
    code.push_str("    let mut writes: HashSet<String> = HashSet::new();\n");

    for (fn_name, is_write) in &handlers {
        code.push_str(&format!(
            "    routes.insert(\"{fn_name}\".to_string(), Arc::new({fn_name}) as HandlerFn);\n"
        ));
        if *is_write {
            code.push_str(&format!(
                "    writes.insert(\"{fn_name}\".to_string());\n"
            ));
        }
    }

    code.push_str("    (routes, writes)\n");
    code.push_str("}\n");

    eprintln!("helix-python build: found {} handlers", handlers.len());
    std::fs::write(output_path, code).expect("Failed to write route_map.rs");
}
