#!/usr/bin/env python3
"""Build the public Engram install bundle for release assets and smoke tests."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import tarfile
import tempfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INSTALLER_DIR = ROOT / "installer"
SCRIPTS_DIR = ROOT / "scripts"
SKILL_DIR = ROOT / "skills" / "engram-memory"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_tree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def build_bundle(
    version: str,
    output_dir: Path,
    image_namespace: str,
    server_image_name: str,
    dashboard_image_name: str,
) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts: list[Path] = []

    with tempfile.TemporaryDirectory() as temp_dir_str:
        temp_dir = Path(temp_dir_str)
        bundle_root = temp_dir / "engram-install-bundle"
        bundle_root.mkdir()

        # Include the bootstrap install.sh for lite path
        install_sh = SCRIPTS_DIR / "install.sh"
        if install_sh.exists():
            shutil.copy2(install_sh, bundle_root / "install.sh")
            os.chmod(bundle_root / "install.sh", 0o755)

        shutil.copy2(INSTALLER_DIR / "compose.yaml", bundle_root / "compose.yaml")
        env_template = (INSTALLER_DIR / ".env.template").read_text(encoding="utf-8")
        env_template = (
            env_template
            .replace("__INSTALL_ROOT__", "~/.engram/full")
            .replace("__DATA_DIR__", "~/.engram/full/data")
            .replace("__RELEASE_VERSION__", version)
            .replace("__IMAGE_NAMESPACE__", image_namespace)
            .replace("__IMAGE_TAG__", version)
        )
        (bundle_root / ".env.template").write_text(env_template, encoding="utf-8")
        shutil.copy2(INSTALLER_DIR / "engramctl", bundle_root / "engramctl")
        os.chmod(bundle_root / "engramctl", 0o755)

        skills_root = bundle_root / "skills"
        skills_root.mkdir()
        copy_tree(SKILL_DIR, skills_root / "engram-memory")

        metadata_path = bundle_root / "release-metadata.env"
        metadata_path.write_text(
            "\n".join(
                [
                    "# Generated by scripts/build_install_bundle.py",
                    f"ENGRAM_RELEASE_VERSION={version}",
                    f"ENGRAM_IMAGE_NAMESPACE={image_namespace}",
                    f"ENGRAM_IMAGE_TAG={version}",
                    f"ENGRAM_SERVER_IMAGE_NAME={server_image_name}",
                    f"ENGRAM_DASHBOARD_IMAGE_NAME={dashboard_image_name}",
                    f"ENGRAM_BUILD_TIMESTAMP={datetime.now(timezone.utc).isoformat()}",
                    "",
                ]
            ),
            encoding="utf-8",
        )

        checksums = []
        checksum_files = [
            Path("compose.yaml"),
            Path(".env.template"),
            Path("engramctl"),
            Path("release-metadata.env"),
            Path("skills/engram-memory/SKILL.md"),
        ]
        if (bundle_root / "install.sh").exists():
            checksum_files.append(Path("install.sh"))
        for rel_path in checksum_files:
            checksums.append(f"{sha256_file(bundle_root / rel_path)}  {rel_path.as_posix()}")
        (bundle_root / "checksums.txt").write_text("\n".join(checksums) + "\n", encoding="utf-8")

        bundle_tar = output_dir / "engram-install-bundle.tar.gz"
        with tarfile.open(bundle_tar, "w:gz") as tar:
          tar.add(bundle_root, arcname=".")
        artifacts.append(bundle_tar)

        bundle_sha = output_dir / "engram-install-bundle.sha256"
        bundle_sha.write_text(f"{sha256_file(bundle_tar)}  {bundle_tar.name}\n", encoding="utf-8")
        artifacts.append(bundle_sha)

        skill_tar = output_dir / "engram-memory-skill.tar.gz"
        with tarfile.open(skill_tar, "w:gz") as tar:
            tar.add(SKILL_DIR, arcname="engram-memory")
        artifacts.append(skill_tar)

        skill_sha = output_dir / "engram-memory-skill.sha256"
        skill_sha.write_text(f"{sha256_file(skill_tar)}  {skill_tar.name}\n", encoding="utf-8")
        artifacts.append(skill_sha)

    return artifacts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default=os.environ.get("ENGRAM_RELEASE_VERSION", "dev"))
    parser.add_argument("--output-dir", default=str(ROOT / "dist" / "install"))
    parser.add_argument("--image-namespace", default="ghcr.io/engram-labs")
    parser.add_argument("--server-image-name", default="engram-server")
    parser.add_argument("--dashboard-image-name", default="engram-dashboard")
    args = parser.parse_args()

    artifacts = build_bundle(
        version=args.version,
        output_dir=Path(args.output_dir),
        image_namespace=args.image_namespace,
        server_image_name=args.server_image_name,
        dashboard_image_name=args.dashboard_image_name,
    )

    print("Built artifacts:")
    for artifact in artifacts:
        print(artifact)


if __name__ == "__main__":
    main()
