"""M1.1 machinery classifier: corpus-measured rates + shape coverage.

The corpus at ``tests/rigs/salience_corpus.json`` is hand-labeled REAL capture
traffic pulled from the live dogfood brain via ``GET /api/episodes``
(2026-07-22). Gates: zero false positives on substantive content, machinery
recall > 0.8.
"""

from __future__ import annotations

import json
from pathlib import Path

from engram.config import ActivationConfig
from engram.ingestion.salience import (
    SALIENCE_MACHINERY,
    SALIENCE_SUBSTANTIVE,
    classify_salience,
    decode_salience_class,
    encode_salience_class,
    is_machinery,
    is_observation_source,
    vector_index_exempt,
)
from engram.models.episode import Episode

_CORPUS_PATH = Path(__file__).parent / "rigs" / "salience_corpus.json"


def _load_corpus() -> list[dict]:
    with open(_CORPUS_PATH, encoding="utf-8") as fh:
        return json.load(fh)["episodes"]


class TestCorpusRates:
    """Measured rates on real hand-labeled dogfood captures."""

    def test_corpus_shape(self):
        rows = _load_corpus()
        labels = {row["label"] for row in rows}
        assert labels == {"machinery", "substantive"}
        assert len(rows) >= 58
        # Distinctness gate: the original corpus passed >=60 via 2 duplicated
        # rows — duplicates must never pad the size gates again.
        ids = [r.get("episode_id") or r.get("id") for r in rows]
        assert len(ids) == len(set(ids))
        assert sum(1 for r in rows if r["label"] == "machinery") >= 20
        assert sum(1 for r in rows if r["label"] == "substantive") >= 30

    def test_zero_false_positives_on_substantive_content(self):
        rows = [r for r in _load_corpus() if r["label"] == "substantive"]
        false_positives = [
            row
            for row in rows
            if classify_salience(row["content"], row["source"]) == SALIENCE_MACHINERY
        ]
        assert false_positives == [], (
            f"{len(false_positives)}/{len(rows)} substantive episodes misclassified "
            f"as machinery: {[r['content'][:80] for r in false_positives]}"
        )

    def test_machinery_recall_above_gate(self):
        rows = [r for r in _load_corpus() if r["label"] == "machinery"]
        caught = sum(
            1
            for row in rows
            if classify_salience(row["content"], row["source"]) == SALIENCE_MACHINERY
        )
        recall = caught / len(rows)
        assert recall > 0.8, f"machinery recall {recall:.3f} ({caught}/{len(rows)}) <= 0.8"


class TestMachineryShapes:
    """Targeted shapes from the M1.1 spec (full frames, beyond the 200-char
    corpus truncation)."""

    def test_task_notification_xml_frame(self):
        content = (
            "[user|Engram] <task-notification>\n"
            "<task-id>wixqg9mwq</task-id>\n"
            "<tool-use-id>toolu_01M4qmn3MLYm4yhGAfQrmKAb</tool-use-id>\n"
            "<output-file>/private/tmp/tasks/wixqg9mwq.output</output-file>\n"
            "</task-notification>"
        )
        assert is_machinery(content, "auto:prompt")

    def test_stripped_tool_use_id_dump(self):
        content = (
            "[user|Engram]  \n bm6s67jbk \n toolu_017nUmqBJ7VsfW9BP57M1GSn \n "
            "/private/tmp/claude-501/tasks/bm6s67jbk.output"
        )
        assert is_machinery(content, "auto:prompt")

    def test_system_reminder_frame(self):
        content = "<system-reminder>Background task b1 completed.</system-reminder>"
        assert is_machinery(content)

    def test_local_command_stdout_frame(self):
        content = "<local-command-stdout>4864 passed in 132.1s</local-command-stdout>"
        assert is_machinery(content)

    def test_exit_code_dump(self):
        content = "Exit code 1\nFAILED tests/test_x.py::test_y - AssertionError"
        assert is_machinery(content)

    def test_path_spam(self):
        content = (
            "/Users/k/Engram/server/engram/main.py "
            "/Users/k/Engram/server/engram/config.py "
            "/Users/k/Engram/server/tests/conftest.py"
        )
        assert is_machinery(content)

    def test_harness_caveat_boilerplate(self):
        content = (
            "Caveat: the messages below were generated by the user while running "
            "through Claude Code. The user may not have seen these messages."
        )
        assert is_machinery(content)

    def test_session_lifecycle_and_compaction(self):
        assert is_machinery("[session-start|Engram] New session started")
        assert is_machinery("[session-end|konnermoshier] Session ended")
        assert is_machinery(
            "[compaction|Engram|2317d745] Context compaction; promotion window compact_2e19"
        )

    def test_empty_content_is_machinery(self):
        assert is_machinery("")
        assert is_machinery("   \n  ")


class TestSubstantiveGuards:
    """False-positive guards: genuine content that superficially resembles
    machinery must stay substantive."""

    def test_path_prefixed_genuine_prompt(self):
        content = (
            "[user|MachineShopScheduler] /Users/konnermoshier/Downloads/Amex_Skills.docx "
            "This is for a potential job opportunity to move from manufacturing."
        )
        assert classify_salience(content, "auto:prompt") == SALIENCE_SUBSTANTIVE

    def test_slash_command_prompt(self):
        content = "[user|Engram] /goal docs/product/AGENT_EXPERIENCE_GOAL.md complete this"
        assert classify_salience(content, "auto:prompt") == SALIENCE_SUBSTANTIVE

    def test_prose_mentioning_exit_code(self):
        content = (
            "[assistant|Engram] The build failed with exit code 1 because the "
            "fixture path moved; fixed by updating conftest."
        )
        assert classify_salience(content, "auto:response") == SALIENCE_SUBSTANTIVE

    def test_prose_with_commit_hashes(self):
        content = (
            "[user|Engram] Confirm CI green on 7a9dd0d (gh run list --branch main "
            "--limit 1; rerun --failed if evicted per the 6-for-6 policy)."
        )
        assert classify_salience(content, "auto:prompt") == SALIENCE_SUBSTANTIVE

    def test_one_word_genuine_prompt(self):
        assert classify_salience("[user|Engram] continue", "auto:prompt") == (SALIENCE_SUBSTANTIVE)


class TestVectorIndexExemptPredicate:
    """The predicate capture and the mop vector drain share (Lane A wiring)."""

    def _episode(self, **kwargs) -> Episode:
        defaults = {"id": "ep_x", "content": "Konner prefers local-first tools."}
        defaults.update(kwargs)
        return Episode(**defaults)

    def test_persisted_machinery_class_wins(self):
        ep = self._episode(salience_class=SALIENCE_MACHINERY)
        assert vector_index_exempt(ep) is True

    def test_persisted_substantive_class_wins(self):
        ep = self._episode(
            content="[session-end|Engram] Session ended",
            salience_class=SALIENCE_SUBSTANTIVE,
        )
        assert vector_index_exempt(ep) is False

    def test_unclassified_falls_back_to_encoding_context(self):
        ep = self._episode(encoding_context='{"salience_class": "machinery"}')
        assert vector_index_exempt(ep) is True

    def test_unclassified_falls_back_to_content_classification(self):
        ep = self._episode(content="[session-end|Engram] Session ended")
        assert vector_index_exempt(ep) is True
        assert vector_index_exempt(self._episode()) is False

    def test_kill_switch_disables_exemption(self):
        cfg = ActivationConfig(salience_gated_embedding_enabled=False)
        ep = self._episode(salience_class=SALIENCE_MACHINERY)
        assert vector_index_exempt(ep, cfg) is False

    def test_enabled_cfg_keeps_exemption(self):
        cfg = ActivationConfig(salience_gated_embedding_enabled=True)
        ep = self._episode(salience_class=SALIENCE_MACHINERY)
        assert vector_index_exempt(ep, cfg) is True


class TestSalienceClassEncoding:
    """encoding_context JSON embedding used by sqlite and helix serialization."""

    def test_empty_class_is_byte_identical(self):
        assert encode_salience_class(None, "") is None
        assert encode_salience_class('{"arousal": 0.5}', "") == '{"arousal": 0.5}'

    def test_encode_into_empty_context(self):
        encoded = encode_salience_class(None, SALIENCE_MACHINERY)
        assert json.loads(encoded) == {"salience_class": "machinery"}

    def test_encode_merges_with_existing_json_object(self):
        encoded = encode_salience_class('{"arousal": 0.5}', SALIENCE_SUBSTANTIVE)
        assert json.loads(encoded) == {"arousal": 0.5, "salience_class": "substantive"}

    def test_encode_leaves_non_json_context_untouched(self):
        assert encode_salience_class("obs_cluster::abc", SALIENCE_MACHINERY) == "obs_cluster::abc"
        assert encode_salience_class("[1, 2]", SALIENCE_MACHINERY) == "[1, 2]"

    def test_decode_round_trip(self):
        for cls in (SALIENCE_MACHINERY, SALIENCE_SUBSTANTIVE):
            assert decode_salience_class(encode_salience_class(None, cls)) == cls

    def test_decode_tolerates_garbage(self):
        assert decode_salience_class(None) == ""
        assert decode_salience_class("") == ""
        assert decode_salience_class("obs_cluster::abc") == ""
        assert decode_salience_class("[1]") == ""
        assert decode_salience_class('{"salience_class": 3}') == ""


class TestObservationSource:
    def test_observation_sources(self):
        assert is_observation_source("mcp_observe")
        assert is_observation_source("mcp_observe_attachment")
        assert is_observation_source("api_auto_observe")
        assert is_observation_source("axi")
        assert is_observation_source("axi:write")
        assert is_observation_source("auto:prompt")
        assert is_observation_source("auto:response")

    def test_non_observation_sources(self):
        assert not is_observation_source(None)
        assert not is_observation_source("")
        assert not is_observation_source("mcp_remember")
        assert not is_observation_source("test")
        assert not is_observation_source("claude-code")
